version: '3'

networks:
  dedeichman:
    driver: bridge

volumes:
  virtuoso_data: {}

services:
  virtuoso_setup:
    container_name: virtuoso_setup
    image: alpine
    volumes:
      - ./config:/config
      - virtuoso_data:/data
    command:
      - "cp"
      - "/config/virtuoso.ini"
      - "/data/"

  virtuoso:
    container_name: virtuoso
    image: "digibib/virtuoso:29c4f313cdcc7d5cd1e331906b0d77b9363679ef"
    networks:
      - dedeichman
    depends_on:
      - virtuoso_setup
    volumes:
      - "virtuoso_data:/data"
    ports:
      - 8890:8890